### ISSUE TITLE
проблема з підписом підчас тесту

### ISSUE THREAD

**Issue by akaJes** [dstucrypt/agent#51]
jes@jes-MS-7680:~/jes/key/agent$ node -v
v18.16.0
jes@jes-MS-7680:~/jes/key/agent$ npm -v
9.6.2
jes@jes-MS-7680:~/jes/key/agent$ test/test.sh
PASS. Decrypt p7s message
PASS. Decryption error when own cert is not supplied
PASS. Decryption error when sender cert is not supplied
PASS. Decrypt transport message without sender ceritifcate
PASS. Decryption error when own cert is not supplied
PASS. Unwrap signed message
PASS. Unwrap signed message but complain about unknown cert
PASS. Unwrap signed transport message
PASS. Sign message and unwrap
Internal error TypeError: Cannot read properties of undefined (reading 'algorithm')
    at /home/jes/jes/key/agent/node_modules/jkurwa/lib/spec/dstszi2010.js:98:49
    at DERNode.use [as _use] (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/encoders/der.js:245:14)
    at DERNode._getUse (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:439:27)
    at DERNode.encode [as _encodeValue] (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:568:21)
    at DERNode.encode [as _encode] (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:490:23)
    at DERNode.encodeChoice [as _encodeChoice] (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:606:15)
    at DERNode.encode [as _encodeValue] (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:527:19)
    at DERNode.encode [as _encode] (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:490:23)
    at DERNode.<anonymous> (/home/jes/jes/key/agent/node_modules/jkurwa/node_modules/asn1.js/lib/asn1/base/node.js:543:25)
    at Array.map (<anonymous>)

  "dependencies": {
    "encoding": "^0.1.12",
    "gost89": "^0.1.11",
    "jksreader": "^1.0.0",
    "jkurwa": "^1.20.1",
    "yargs": "1.3.x"
  }

**Comment by akaJes** [comment]
due the asn1.js project is stale possible to make the changes to kurwa project's depdencies for the fixed branch of this commit https://github.com/muromec/asn1.js/commit/7ca2c330ec52fbb5676dd4d54f55fb95b778ba91 ?
it could be possible like this https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls

**Comment by muromec** [comment]
Пришліть PR чи шо

**Comment by akaJes** [comment]
https://github.com/dstucrypt/jkurwa/pull/47
